// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Note: this only affects the Prisma CLI (db pull, migrate, studio...).
  // The running app builds its own connection via @prisma/adapter-pg from
  // DATABASE_URL directly (see src/config/prisma.ts) and is unaffected.
  //
  // The CLI needs the session pooler (port 5432, no pgbouncer) because
  // introspection/migrations hang indefinitely on the transaction pooler
  // (port 6543) — it doesn't support the prepared statements they require.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
